ethereum/ethereum-org

bin/install.sh

When the `install.sh` script is run on a linux distro without the apt-get package manager the script doesn't stop and print an appropiate message to the user. This PR will abort the script and inform the user that he is on an unsupported platform. It also enables backslash interpretation for the echo command to interpret newlines in the abortInstall function.

abort install script on linux distro without apt-get package manager

---

bin/install.sh

Looked at versions 0.82.7.5, 0.92.36, and 0.96.8 of software-properties
(This is equivalent to what Ubuntu precise, trusty, utopic, and wily provides. Or basically "any version of Ubuntu".)
http://packages.ubuntu.com/wily/software-properties-common
There has never been a -q option to add-apt-repository. So this was definitely an error.

-q is not an option of add-apt-repository

---

bin/install-cpp.sh

In most Unix scripts when you are queried with a [Y/n] it is
always interpreted that the capitalized option is the default
(chosen by simply pressing Enter).
So we are adding Yes as the default option.

Provide default value in Linux install prompt

---

views/cli.jade
views/content/cli.md
views/content/crowdsale.md
views/content/dao.md
views/content/ether.md
views/content/greeter.md
views/content/token.md
views/mixins/recipes.jade

A few links were dead, so I went through and cleaned up any ones that seemed stale.
Also, some of the jade recipes were href'ing to relative anchors. The anchors links would only work on the [main page](https://www.ethereum.org/), and not when viewed on sub pages on [Greeter](https://www.ethereum.org/greeter), or [Ether](https://www.ethereum.org/ether).  I changed these links to absolute anchors so the links work both on the index page, as well as the full sub-pages (/cli, /ether, /greeter, etc.)

general cleanup of href links in .md files, as well as in jade recipes

---

bin/install-go.sh

Trying to install with:
bash <(curl https://install-geth.ethereum.org -L)
shows a question where the default option is incorrectly uppercased:
...
I understand, I want to install Geth (ethereum CLI) (Y/n)      
==> Installation failed
==> Process stopped by user. To resume the install run the one-liner command again.
Pressing only Enter (without entering any option) aborts the installation. Even when Yes is displayed as default.
**The default option is n (for no) and it should be uppercased instead of Y.**

Default option in install script with wrong uppercase order

---

views/content/ether.md

Otherwise it returns
> web3.fromWei(eth.getBalance(web3.eth.accounts[0]), "ether")
(shell):1: ReferenceError: eth is not defined
web3.fromWei(eth.getBalance(web3.eth.accounts[0]), "ether")
^
ReferenceError: eth is not defined
at (shell):1:14
Error: Uncaught ReferenceError: eth is not defined

web3. before eth.getBalance

---

views/content/cli.md
views/content/ether.md

The instructions referenced a code block as being "above" when the code block
was below the text.

Make eth installation instructions clearer

---

views/content/cli.md
views/content/crowdsale.md
views/content/dao.md
views/content/ether.md
views/content/foundation.md
views/content/greeter.md
views/content/token.md
views/includes/footer.jade
views/mixins/recipes.jade

There were many potential editing issues I noticed and chose not to fix. Most of these would require either subjective style choices or more information than I had available.
- Inconsistent use of "-sation" versus "-zation". (3 matches versus 34 matches)
- It's unclear whether "ether" is countable or uncountable.
* `The funding goal is the amount of ether to be raised`
* `If the proposal passed then you should be able to see Bob's ethers arriving on his address`
- Inconsistent use of "amongst" and "among". (1 match vs 2 matches)
- Inconsistent capitalization of "Ethereum" in plain text.
* `Finally, by creating your token in Ethereum, your coin will be compatible with any other contract running on ethereum`
- Mixed and inconsistent use of words and digits in plain text numerals.
* `If you …

Fix typos, remove duplicate directions and project list entry

---

views/content/dao.md

`_position >= -1 || _position <= 1` is always true but this method should check if `_position` is `-1`, `0` or `1`:
> `+1 for voting yea, -1 for voting nay, 0 abstains but counts as quorum`

Fixed condition in Democracy.vote method

---

views/content/cli.md

I think there is a copy & paste error in the section describing how to install geth on OSX:
It says `Then use these commands to install cpp-ethereum` when you really mean `Then use these commands to install ethereum`

When installing geth, do not say you're installing cpp-ethereum

---

views/content/dao.md

Replace repeat of "former" with "latter" and reword slightly for clarity.

Fix typo in DAO tutorial

---

views/content/cli.md

Fixed link to "What is ether?", removed non-existent "The Ethereum Ecossystem"

Updating broken links

---

views/content/token.md

When I copy & paste the snippet, I was getting `Identifier already declared error`.
I also noticed that [the full code](https://www.ethereum.org/token#the-code) does not raise error because both `buy()`  and `sell()` functions do not have return values which are different from the code snippets.

Remove duplicate type declaration

---

views/content/token.md

1. Renamed `myToken` to `MyToken`.
2. Typo about contact details (it's on the right, not left).
3. Removed unneeded white spaces.

Typos + removed white spaces

---

views/content/token.md

`is owned` modifier should be added to the contract, not function (as seen further down in the full code sample).

FIx code typo

---

views/content/dao.md

This PR contains minor changes to [dao.md](https://github.com/ethereum/ethereum-org/blob/master/views/content/dao.md):
- Fixed some typos
- Removed duplicated words
- Changes text formatting where applicable for consistenct
- Removed unnecessary whitespaces

Fixed typos and text formatting in dao.md

---

views/content/dao.md

According to source blog post https://blog.ethereum.org/2015/12/07/ethereum-in-practice-part-3-how-to-build-your-own-transparent-bank-on-the-blockchain/
Fixex issue https://github.com/ethereum/ethereum-org/issues/222

Fixes typo

---

views/content/crowdsale.md
views/content/dao.md
views/content/token.md

- **Replace stakeholder by shareholder in the tutorials**
Strictly speaking it's not incorrect as shareholders are special kind of stakeholders that owns share of an organisation. But I find it confusing that the two terms are swapped seemingly at random. I kept looking for in the code and the description if this smart contract would differentiate stakeholders from shareholders or if that was a spelling mistake. Or maybe I missed something important in the tutorial?
- **Remove mention of th greeter in the DAO tutorial**
The greeter example isn't available from the landing page of Ethereum, so it might be confusing for people that don't know what this refers to.

Replace stakeholder by shareholder in the tutorials

---

views/content/crowdsale.md

The indicated number of blocks is wrong based on the provided formula above. For 60 minutes, if a new block is created every 17 seconds, you will have to wait for 212 blocks (+ buffer)

Adjust number of blocks to reflect formula above

---

views/content/token.md

Ethereum wallet complains when 'uint revenue' is re-declared.

Remove 'uint' from the sell example

---

views/layout.jade

This updates the GA tracking ID to be under the same account as the Blog GA.
The existing tracking ID is associated with an account which is no longer under EF control

Update Google Analytics tracking ID

---

views/content/dao.md

Hi, everyone!
This paragraph has the same meaning of the next one. The reason I decided to remove this one instead of the next is because the list of fields/values makes things easier to understand.

Remove duplicate paragraph

---

views/content/dao.md

No value is ever returned from executeContract(), so it's better to avoid promising a return value that is never delivered.

Made return types consistent with implementations in example code

---

views/content/token.md

In order to prevent users mistakenly transfering to 0x0 address, here's a recommendation to validation at the contract level.
Burning token value would be accomplished by calling the `burn(address _to, uint256 _value)` method.

Adding token burn method

---

views/content/token.md

There is a bug where if the constructor for MyAdvancedToken is called, specifying a centralMinter different from msg.sender, then the initial supply of tokens is given out twice, to two different addresses.
MyAdvancedToken first makes a call to the super constructor (token), which sets the balance of msg.sender to initialSupply ('balanceOf[msg.sender] = initialSupply;'). Then the constructor for MyAdvancedToken changes the owner to centralMinter ('if(centralMinter != 0 ) owner = centralMinter;') and then sets the balance of owner=centralMinter to initialSupply ('balanceOf[owner] = initialSupply;').
If "msg.sender" and parameter "centralMinter" are different addresses then the actual total supply of coins is 2 * initialSupply = 2 * totalSupply.
This is undesired behaviour.

Remove bug from example token contract

---

views/content/token.md

Line 547 on token.md throws an error
ie. line 63 on MyAdvancedToken - I think this line in the contract is erroneous 
`
/* Allow another contract to spend some tokens in your behalf */
function approve(address _spender, uint256 _value)
returns (bool success) {
allowance[msg.sender][_spender] = _value;
// tokenRecipient spender = tokenRecipient(_spender); // Error
return true;
}
`
Error: 
Unused local variable
tokenRecipient spender = tokenRecipient(_spender);
^--------------------^
It already exists in the next function
`
/* Approve and then communicate the approved contract in a single tx */
function approveAndCall(address _spender, uint256 _value, bytes _extraData)
returns (bool success) {    
tokenRecipient spender = tokenRecipient(_spender);
if (approve(_spender, _value)) { …

Removed erroneous line (547)

---

views/content/greeter.md

* It was a bit confusing to hop into this tutorial right away without the context on (1) having installed geth and (2) the smart contract file type / compiler etc.
* Couple of minor typos

Add prerequisites and correct minor typos.

---

views/content/cli.md

Links to parity.io and parity.io/parity were outdated. Company renamed itself from Ethcore to Parity Technologies.

Update links for the Parity client

---

views/content/crowdsale.md

Without the `+`, the `balanceOf` mapping only keeps track of the last purchase an account makes. 
I.e, if an account participates in the crowdsale multiple times, the coin sale fails and an account asks for a refund, the account won't get all of its Ether back.

keep track of balance for multiple coin purchases

---

Gruntfile.js

I noticed that in the middle of https://ethereum.org/js/frontier.min.js there is some non-minified code coming from `numeral.js`. `numeral.js` is treated as vendor and right now vendor files aren't passed through `uglify`.
Following the same pattern as `app.js`, I updated the Gruntfile to minify the vendor scripts as well. It reduces the final build by ~20 KB. I renamed also `scripts -> app` (I find it less confusing this way).

Minify vendor scripts

---

views/content/greeter.md

At this point in the tutorial it is likely that the reader does not have solidity installed, so it probably makes sense to link to where/how to install it. I've included one link I found but if there is a better link that could be included as well. It seems other parts of this page may be out of date but this sentence should help.

Add link to solidity install instructions

---

views/content/token.md

**Motivation for pull request**
Solidity 0.4.10 introduced the ```require()``` syntax which throws if the condition is false. The changes made in this PR are aimed at replacing the ```if ... throw()``` statements. This is done to encourage the behavior shown in the official Solidity documentation.
**Testing**
All code compiles with 0.4.11
If there is anything wrong or something that needs to be improved/changed feel free to say so, this is my first pull request for this project so I'm not yet familiar with the exact workflow.

Replace 'if ... throw()' with 0.4.10 require() syntax

---

views/content/cli.md

Links for Parity Client were outdated. Company changed it's name to Parity Technologies.

Update Links for Parity Client

---

views/content/token.md

This PR removes the final mentions of the ```throw()``` function from the token example to make sure it compiles without any errors (due to the fact ```throw()``` is now considered to be deprecated).
Compiles now without any issues/errors.

Remove final throw() functions in the token example

---

views/content/crowdsale.md

`addressOfTokenUsedAsReward` should be of type `address` as the name suggests. While solc doesn't complain about the current implementation, I think setting the `address` type conveys the intention better.

Update type signature of `Crowdsale` constructor

---

views/content/token.md

It is impossible to send all balance because of > is bug, at least 0.0000001 part (or so) will stay at old wallet and lost.
Need to use >= instead of course.
Possible problems with payments and automatization, as sending all amount will cause errors.
For example Hubcoin deposits / withdraws at https://etherscan.io/address/0x563383b56367Ff2afFFE5c6BCF9187bBE52d40Ad Hubcoin contract was failed on CoinExchange.io because of it bug.

Update token.md from example on Ethereum.org index page

---

views/content/token.md

It is impossible to send all balance because of > is bug, at least 0.0000001 part will stay at old wallet and lost.
Need to use >= instead of course.
Possible problems with payments and automatization, as sending all amount will cause errors.
For example Hubcoin deposits / withdraws at https://etherscan.io/address/0x563383b56367Ff2afFFE5c6BCF9187bBE52d40Ad Hubcoin contract was failed on CoinExchange.io because of it bug.

Token: >= instead > (Impossible to send last coin)

---

public/css/style.css

Browsing ethereum.org on mobile, I noticed a lot of funky center aligns.
I checked the css and there is a global .row{text-align:center;} on screens <600px.
This PR is a suggestion to remove that in favor of staying default left aligned.
Screenshots before/after:

Align left on mobile

---

Gruntfile.js
views/layout.jade

Updated Gruntfile to compile to `app.css` and `app.js` (instead of `frontier.css` and `frontier.js`)

Update CSS/JS file names to remove frontier reference

---

views/content/token.md

This commit fixes a typo in the docs located here:
https://ethereum.org/token#proof-of-work

Fixes typo: Change ccount to account

---

views/content/ether.md

In the section "CPU MINING USING THE COMMAND LINE"
it read: "You only need to this once."
Updated to read: "You only need to do this once."

Add word missing to to make grammatically correct.

---

solidity/crowdsale.sol

Was getting a compile error as `This declaration shadows an existing declaration`.
hence, changed 
`event GoalReached(address beneficiary, uint amountRaised);` 
to 
`event GoalReached(address recipient, uint totalAmountRaised);`

Updated "event GoalReached" parameters labels to avoid compile error

---

dist/foundation.html
views/content/foundation.md

closes #760 
It seems that Vitalik's personal site location has changed from https://vitalik.ca to http://vitalik.ca.
The ethereum org site now correctly points to Vitalik's personal site.

Modify Vitalik's website location

---

views/content/token.md

.send(...) is now deprecated.
Send vs transfer comparsion:
https://vomtom.at/solidity-send-vs-transfer/
Also the Solidity by Example Documentation got updated and now uses the .transfer() function.
http://solidity.readthedocs.io/en/develop/solidity-by-example.html
We dont need to use require, as transfer fully propagates errors.

Updating deprecated .send(...) to .transfer(...)

---

views/content/cli.md

**"The console has auto completion and history support"**
_was changed to:_
**"The console has auto completion of commands and command-history support"**

Fixed phrase for better clarity.

---

views/content/greeter.md

this line had been duplicated
"If you have not installed a compiler, then you need to install one. You can find [instructions for installing Solidity here](http://solidity.readthedocs.io/en/develop/installing-solidity.html)."

remove duplicated line

---

views/content/cli.md

The command '**admin.nodeInfo.nodeURL**', results in '**undefined'**, in the recent version of Geth.
_Here is the actual output, based on the recent version of Geth:_
> myMac:console2 admin$ geth attach ipc:../node2/geth.ipc 
> Welcome to the Geth JavaScript console!
> 
> instance: Geth/v1.7.3-stable/darwin-amd64/go1.9.2
> coinbase: 0x3fd97155061e47960b59b563a178fa248493017c
> at block: 2 (Thu, 11 Jan 2018 20:25:58 +04)
>  datadir: /Users/admin/MyXyz/testnet/node2
>  modules: admin:1.0 clique:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
> 
> \> web3.eth.accounts
> ["0x3fd97155061e47960b59b563a178fa248493017c"]
> \> admin.nodeInfo.nodeURL
> undefined
> \> admin.nodeInfo.enode
> "enode://f48fcf69ba27442ff3813912ec12ea1ad249f14739dabfcadb3985c3654540e047700 …

[admin.nodeInfo.nodeURL] >> [admin.nodeInfo.enode]

---

views/content/token.md

Without declaring 'public' on this function, Ethereum Wallet returns the error:
```
No visibility specified. Defaulting to "public".
function Token(uint256 initialSupply)  {
^
Spanning multiple lines.
```
Proposing to add that in so tutorial takers don't run into this error, get confused, etc.

Add necessary 'public' to function in tutorial

---

views/content/greeter.md

It seems like the UI for [Remix](https://remix.ethereum.org/) changed since this tutorial was last updated. 
I edited some content so that the instructions match the new UI. The user can now retrieve the `Web3Deploy` compiled code and `ABI` by following the instructions.
I also made it clearer that the user can choose between using Remix or downloading Solc. Last but not least, there are a few formatting changes in those sections.
This is my first pull request to the ethereum project, so I'm not entirely sure how to process works. Let me know if I didn't follow the guidelines!

Update Greeter tutorial to comply with change in Remix's UI

---

views/content/greeter.md

While trying to get up and running with contract deployment through geth, I spent multiple hours trying to debug the `greeterFactory.new(...)` command in this tutorial without realizing that I was getting an "Error: exceeds block gas limit" error. This change makes it so that the console will log if contract deployment fails.

Add error handling to Greeter tutorial

---

solidity/token-advanced.sol
solidity/token-erc20.sol
views/content/token.md

Hi,
as an exercice to learn how to use Truffle, I'm developping an ERC20 token test suite.
I realised that the ERC20 token on ethereum.org does not comply with the ERC20 token standard <:o)  !!!
If you look at the ERC20  token standard, here:
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#transfer
You can read that:
Transfers of 0 values MUST be treated as normal transfers and fire the Transfer event.
But in  the example, you are too strict when checking for overflows. A 0 token transaction will revert.
I think we need to change the > into >= to allow successful transfers of 0 token as required by the standard.

Transfer of zero ERC20 Token must success

---

views/content/greeter.md

Reverts ethereum/ethereum-org#792
The changes in pull request #792 don't make much sense. The one line of documentation that was added conflicts with the line right below it, so I have a feeling this was done by accident.
Looking at the commits in #792, it seems like there are a ton of changes that didn't get merged in. Perhaps the commits were not merged correctly?

Revert #792

---

views/content/token.md

This pull request adds the `public` visibility to the two variables in the MyToken example that lack any explicit visibility.  I have made this change for a couple reasons:
* **Consistency.**  All of the other variables in this example use the `public` visibility and its omission on these two variables raises questions as to what makes them unique.  There is currently no justification in the example for the discrepancy so I believe it is simply an oversight.
* **Correctness.**  I believe it is a bug for `currentChallenge` to not be `public`.  Without the `public` visibility, a user cannot easily determine what the current challenge problem they are trying to solve is.

Add 'public' visibility to two variables in MyToken example

---

public/css/style.css

Addresses issue #819 
The reason for -30px is because of the margins generated by bootstraps __.row__ class which has -15px margin left and -15px margin right.
It only applies to screens with max-width: 800px

Removed horizontal overflow generated by figures on mobile

---

views/includes/footer.pug

https://github.com/ethereum/wiki/wiki contains a wealth of information, that is frequently updated, from an introductory level to advanced. Thus, it would be good to link to it on the website.

Link to wiki

---

views/content/cli.md

1. The network ID mentioned in the Geth command and the supporting text are different. Updated the command's network ID to match.
2. Adding more context to the two Geth commands being used.

Updating network ID typo and providing more context to Geth commands

---

solidity/token-advanced.sol

external should be used for interfaces rather than public, and emit should be prefixed for invoking events.

prefixing emit for events as non usage of emit for invocation is depricated

---

solidity/token-advanced.sol

As discussed in https://github.com/ethereum/solidity/issues/4116
Due to solidity compiler change after v0.4.22, this wrong transfer function will cause serious issues.
We (SECBIT.IO) found many people followed this tutorial on ethereum.org.
SHOULD fix this ASAP!

make transfer func compatible to eip20 standard

---

views/includes/footer.pug

Fixing wiki link spacing on footer

---

solidity/token-erc20.sol

> MUST trigger on any successful call to approve(address _spender, uint256 _value).
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#approval
We audited many tokens without event Approval.
Should comply EIP20 for a better dApp ecosystem.

token-erc20: add event Approval to follow eip20

---

views/content/dao-congress.sol

removeMember needs to tidy up the memberId mappings, else the whole member system will break upon calling removeMember

fix a glaring bug in removeMember

---

views/content/cli.md

- Fix level of "Other options" heading
- Consistently use two blank lines before each section heading
- Normalize capitalization and punctuation of section headings
- Format the Python client as bold, to match the C++ and Go ones
- Change "Mac" to "macOS"
- Fix capitalization of "apt-get" and format as code

CLI docs: standardize headings + minor tweaks

---

views/content/token.md

Both line 273 and line 280 repeated this: "all accounts are unfrozen by default..." and have very similar meanings. This is odd to read. Updated to make this section flow a bit better, and be a bit clearer.

Improved clarity in freezing accounts

---

views/content/token.md

Code example is already in the new syntax.

remove text about old constructor syntax

---

views/content/ether.md

The "who needs ether" section was phrased strangely, they should either have been put into bullet points, or turned into a single sentence. If you try to put it into a single sentence, it leads to the odd repetition of "and" in the same sentence. I decided to use bullet points, even though it might have been overkill for just 2 items.
Either way works, but the original certainly doesn't read right.

Fix formatting error in "who needs ether"

---

views/content/cli.md

Provide a link for creating the genesis block _before_ the command which depends on it.  (The existing instructions are out of date, after the command, and do not contain the presupposed file name, and hence do not show up in a search.)

Provide a link for creating the genesis block
