views/mixins/recipes.jade

I think this was supposed to be "An", not "And".

'An' instead of 'And'

---

views/content/greeter.md

My English teacher would be rolling in her grave for "that that".

that that = bad

---

views/content/geth.md

Add license and auto completion

---

views/mixins/recipes.jade

Maker Dao  | Autonomous bank & market maker
i'm working as designer at maker DAO!
If you wanto to get a confirmation before update .. pls contact rune@makerdao.com or me at cass@makerdao.com

Maker DAO - subtitle update

---

views/content/crowdsale.md
views/content/dao.md
views/content/greeter.md
views/content/token.md

in example codes to send contracts

Missing string concat operator

---

views/content/token.md

I've deployed a test registrar and tested.

tokenName, myName is undefined

---

views/content/greeter.md

don't waste user's gas, 300,000 worked fine.

300,000 is fine, 1,000,000 not needed for greeter

---

views/mixins/recipes.jade

Clear spelling issue on the homepage. Fixed and ready to push live.

Spelling fix for approximately. Closes #107

---

views/content/dao.md
views/content/token.md

Fixes some spelling errors in the public docs.

Fix minimal spelling errors

---

Gruntfile.js
views/content/donate.md
views/content/timeline.md
views/donate.jade
views/includes/footer.jade
views/index.jade
views/mixins/recipes.jade

This is the most important pull request

Unicorn Typo

---

views/content/cli.md

just fixed the download path url

fix windows download path

---

bin/install-cpp.sh

Adding package name to `apt-get remove` command.
This fixes issue #155.

Fix for issue #155

---

views/content/foundation.md
views/donate.jade
views/includes/footer.jade
views/index.jade

* Update on foundation text
* Update footer

Final updates to page

---

views/content/cli.md
views/index.jade

On win32 replaces the direct download link with a ‘not supported yet’ text

Monday updates to site

---

views/index.jade

Credit goes to: https://www.reddit.com/r/ethtrader/comments/49e0hl/new_ethereum_website_homestead_release_now_live/d0r6ptl

Typo from reddit

---

views/content/crowdsale.md

Maybe this is some event magic in solidity that I don't know about, but it seems like a bug so I removed it.

Removed incorrect FundTransfer line from Crowdsale

---

views/content/dao.md

Basically formatting and typos fixes

Fixes for dao page

---

views/index.jade

Fixes [#244](https://github.com/ethereum/ethereum-org/issues/244)

Updated Wallet version

---

views/content/dao.md

Fix token links, #234

---

views/content/dao.md

The executeProposal function allowed recursive calling. We can prevent it by updating p.executed before executing the call to an external contract.

Fixes recursive call attack

---

views/content/greeter.md

Context: See EIP 6 (Renaming SUICIDE opcode)

Replace suicide() with selfdestruct()

---

views/content/crowdsale.md
views/content/dao.md
views/content/token.md

This PR fixes some uncheck sends, which prevented a correct distribution of the funds. An unsafe code pattern was also used, where the contract would be stuck if too many funders took part at the same time.

Fixes some unchecked sends/unsafe code example

---

views/content/token.md

Fixes \*\*transfer\* -> \*\*transfer\*\*.
Signed-off-by: Jon Seymour <jon@wildducktheories.com>

docs: balance opening

---

views/index.jade

Added some spaces between words as you can see in the images.
Originally:
Updated:

Add spaces between words

---

views/content/token.md

Hi, everyone!
This PR fixes a missing semicolon on a code snippet (in accordance with [solidity v0.4.0](https://github.com/ethereum/solidity/releases/tag/v0.4.0) changes).

Add missing semicolon

---

views/index.jade

"bootstraped" -> "bootstrap**p**ed"

Fixed spelling mistake on front page

---

README.md

Fix markdown formatting in README.md

---

views/content/token.md

Not a huge deal but just thought it was cleaner to have the orders be consistent :)

Param order cleanup

---

views/content/dao.md

Clean up a sentence so that it reads more clearly.

Small grammatical fix

---

views/content/token.md

burnFrom method should also update sender's allowance. Otherwise, it can burn as much as it wants.

add allowance update to burnFrom

---

views/donate.jade

Bitcoin address had link to blockchain explorer, but not Ether address. Also Bitcoins -> Bitcoin typo fixed

Added href to tipjar address + fixed typo

---

views/content/token.md

- Added spaces around math operators for consistency with the other example code.
- Removed extraneous spaces after variable names.
- Edited some markup to increase clarity.
- Re-arranged a word ("be").

Cleans up the code examples and changes a couple of sentences.

---

views/content/dao.md

I fixed "The Blockchain Congress" chapter of **dao.md**.
- I changed explanations and code according to the latest Ethereum Wallet(0.8.10).

Fix dao md: "The Blockchain Congress" chapter.

---

views/content/token.md

Also, refactors some repeated code into an internal function

Fix basic token contract for updated solidity

---

views/content/token.md

in last commit it was broken Alex Van de Sande, he lost one tab for code

fixed markup token.md

---

views/content/crowdsale.md

Cannot increment an uninitialized variable.

Fix a typo/bug in crowdsale contract

---

views/content/token.md

"if the caller should be have permission to move those" => " if the caller should have permission to move those"

Remove extra be

---

views/content/greeter.md

It might also be worthwhile to merge this directly into master and gh-pages to stop confusion being caused amongst new devs.

fixes Greeter tutorial see #14738

---

public/css/style.css
views/includes/footer.jade

A few small changes:
1. Open 'Community' links in new tabs (for a better user experience)
2. Update http to https
3. Add 'blog' class for css selector
4. Capitalize the 't' in YouTube
:)

Open 'Community' links in new tabs

---

views/content/dao.md

Congress contract declaration was missing

fix Congress contract

---

views/content/ether.md

Fixed the link for the reference of frontier git book, mining chapter.

Fix frontier gitbook link

---

views/content/token.md

Type fixes `se  nder` updated with `sender`

---

views/content/ether.md

Based on Byzantium hard fork.
https://blog.ethereum.org/2017/10/12/byzantium-hf-announcement/
Closes https://github.com/ethereum/ethereum-org/issues/632

Update mining reward amount

---

dist/token.html
views/content/token.md

Fix token pages 301 Redirects

---

dist/cli.html
views/content/cli.md

Fix cli page 301 Redirects

---

dist/ether.html
views/content/ether.md

Fix ether pages 301 Redirects

---

dist/greeter.html
views/content/greeter.md

Fix greeter pages 301 Redirects

---

dist/terms-of-use.html
views/content/terms.md

Fix terms pages 301 Redirects

---

views/content/dao.md

Case & space now better match interface.
Comment naming step unnecessarily confuses due to interface mismatch.  
Also, some grammar cleanup.

Docs improvement to match interface

---

views/content/dao.md

It should be "contract Token", not "contract token".
Also transferFrom is missing in the contract, added it to contract Token.

Update contract Token name

---

solidity/token-erc20.sol
views/content/token.md

Corrected some English grammatical mistakes

English grammatical mistakes

---

app.js
package.json

package.json update with updated version and tested on node 6.0.0 and npm 3.8.6

es6 changes,node and npm version update,and 404 handling 

---

solidity/token-erc20.sol

Fix Constructor word typo

---

views/content/cli.md

Changed:
**generate an account**
to:
**create an account**

Rephrased with conventional words.

---

views/content/cli.md

'CAUTION' is a more suitable word than 'ATTENTION', in order to highlight POTENTIAL MONEY LOSS.
For reference, on Technical Writing, visit:
http://www.stevensstrategic.com/technical-writing-the-difference-between-warnings-and-cautions/

 Used 'CAUTION' to highlight POTENTIAL MONEY LOSS.

---

views/content/cli.md

because there are three clients but both implies that there are only two clients

both -> two distinct

---

views/content/dao-association.sol
views/content/dao-liquid-democracy.sol

Update the logic of part of the DAO examples.

Solidity fixes

---

views/includes/footer.pug

Ethereum's Twitter handle was recently updated from @ethereumproject to @ethereum

Update Twitter links

---

subdomains/grants.md
subdomains/hackternship.md

This will eventually be the address for grants.ethereum.org

Created hackternship.md

---

subdomains/grants.md

Updated the grants page

---

solidity/dao-congress.sol

These commits fix warnings when trying to compile dao-congress.sol

Fix dao-congress.sol solidity compiler warnings

---

views/content/token.md

Reused the _transfer function added emit's as prefixes to events

prefixed emit for events.

---

solidity/token-minimal.sol

Same as https://github.com/ethereum/ethereum-org/pull/859.

token-minimal.sol: compatible erc20

---

solidity/token-erc20.sol

Same as https://github.com/ethereum/ethereum-org/pull/859.

token-erc20.sol: compatible erc20

---

solidity/token-advanced.sol

Same as https://github.com/ethereum/ethereum-org/pull/865.

token-advanced: add event Approval to follow eip20

---

views/content/ether.md

PR to solve https://github.com/ethereum/ethereum-org/issues/878
Updates the ether issuance numbers from FAQ page to post-Byzantium ones.

Update ether issuance numbers

---

views/content/dao-time-lock-multisig.sol

removeMember needs to update the memberId mapping else it breaks the whole members system

fix a bug that breaks the members system

---

solidity/crowdsale.sol
views/content/crowdsale.md

Solidity version 0.5.0 was just released, so the example on https://ethereum.org/dao needs to be updated (the current example will not compile).
Related to: https://github.com/ethereum/ethereum-org/pull/919, https://github.com/ethereum/ethereum-org/pull/920 and https://github.com/ethereum/ethereum-org/pull/921

Updates Crowdsale example

---

solidity/dao-time-lock-multisig.sol

the current example have a serious bug in the removeMember method which will mess up the whole members system, the issue is fixed by tidying up the memberId mappings.

fix bug in removeMember
